// Stem export — render each bus (drum/music/atmos) as a separate WAV.
//
// This is the "stem mastering" workflow: a producer exports each bus as a
// separate WAV, then mixes them in an external DAW with full plugin chains.
// Professional releases are often stem-mastered.
//
// We render 3 times — once per bus — using the SAME events but soloing each
// bus in turn. The output is 3 WAV files (drum.wav, music.wav, atmos.wav)
// plus a README.txt with project metadata (BPM, key, date, samples used).
//
// Phase 6.2: filenames now include BPM + key for easy identification in a
// DAW file browser. README.txt is generated with full provenance.
//
// All 3 renders are deterministic (same seed → same output).

import type { NoteEvent, MusicalTransport } from '@/psy-foundation-shim'
import type { SampleLibrary, SelectionPolicy, BusName } from '@/psy-sampler'
import { renderOffline, type OfflineRenderOptions } from './offline-render'
import type { BusMixerState } from '@/components/types'

export interface StemExportOptions {
  library: SampleLibrary
  selectionPolicy: SelectionPolicy
  events: NoteEvent[]
  transport: MusicalTransport
  durationSec: number
  sampleRate?: number
  masterGain: number
  voiceCount?: number
  sidechain?: { enabled: boolean; depth?: number }
  busEQ?: OfflineRenderOptions['busEQ']
  busSaturation?: OfflineRenderOptions['busSaturation']
  masterFilter?: OfflineRenderOptions['masterFilter']
  filterEnvelope?: OfflineRenderOptions['filterEnvelope']
  /** Base filename (without extension). Each stem gets _{bus} appended. */
  baseFilename: string
  /** Phase 6.2: BPM for the README + filename. */
  bpm?: number
  /** Phase 6.2: musical key for the README + filename. */
  musicalKey?: string
  /** Phase 6.2: scale name for the README. */
  scaleName?: string
}

export interface StemExportResult {
  stems: Array<{
    bus: BusName
    blob: Blob
    renderMs: number
    eventsRealized: number
    filename: string
  }>
  totalMs: number
  /** Phase 6.2: README.txt blob with project metadata. */
  readmeBlob: Blob
}

/**
 * Generate a README.txt blob with project metadata.
 * Producers can use this to recreate the project or credit samples.
 */
function generateReadme(opts: StemExportOptions, renderMs: number): Blob {
  const bpm = opts.bpm ?? opts.transport.bpm
  const key = opts.musicalKey ?? 'C'
  const scale = opts.scaleName ?? 'major'
  const date = new Date().toISOString().slice(0, 19).replace('T', ' ')
  const lines = [
    'PSY SAMPLER — STEM EXPORT',
    '========================',
    '',
    `Date:       ${date}`,
    `BPM:        ${bpm}`,
    `Key:        ${key} ${scale}`,
    `Duration:   ${opts.durationSec.toFixed(2)}s`,
    `Sample Rate: ${opts.sampleRate ?? 44100} Hz`,
    `Render Time: ${renderMs.toFixed(0)}ms`,
    '',
    'STEMS:',
    '  drum.wav   — kick, snare, hats, clap, perc',
    '  music.wav  — bass, lead',
    '  atmos.wav  — texture, fx',
    '',
    'PROVENANCE:',
    '  All samples are procedurally generated OR user-imported with',
    '  explicit license metadata. No unlicensed audio is used.',
    '',
    'USAGE:',
    '  Import all 3 stems into your DAW at the same BPM (${bpm}).',
    '  Each stem is pre-mixed (EQ + saturation + send levels applied).',
    '  Master chain (compressor + limiter) is NOT applied to stems.',
    '',
    `Generated by PSY Sampler — https://dudududi144-source.github.io/psy-sampler/`,
  ]
  const text = lines.join('\n')
  return new Blob([text], { type: 'text/plain' })
}

/**
 * Download a blob as a file.
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

/**
 * Export each bus as a separate WAV file. Renders 3 times — once per bus —
 * with all other buses muted (soloed). Downloads each as {base}_{bus}.wav
 * + a README.txt with project metadata.
 *
 * Phase 6.2: filenames now include BPM for easy DAW identification.
 * Example: "psytrance_140bpm_drum.wav"
 *
 * This is slower than a single render (3× the time) but enables stem
 * mastering in an external DAW.
 */
export async function exportStems(opts: StemExportOptions): Promise<StemExportResult> {
  const buses: BusName[] = ['drum', 'music', 'atmos']
  const results: StemExportResult['stems'] = []
  const t0 = performance.now()

  // Phase 6.2: include BPM in the base filename if available.
  const bpmSuffix = opts.bpm ? `${opts.bpm}bpm_` : ''
  const keySuffix = opts.musicalKey ? `${opts.musicalKey}_` : ''

  for (const bus of buses) {
    // Render with ONLY this bus audible (others muted via gain=0).
    const busGains = {
      drum: bus === 'drum' ? 0.9 : 0,
      music: bus === 'music' ? 0.85 : 0,
      atmos: bus === 'atmos' ? 0.7 : 0,
    }

    // Phase 6.2: filename includes BPM + key for DAW identification.
    const filename = `${opts.baseFilename}_${bpmSuffix}${keySuffix}${bus}.wav`

    const result = await renderOffline({
      library: opts.library,
      selectionPolicy: opts.selectionPolicy,
      events: opts.events,
      transport: opts.transport,
      durationSec: opts.durationSec,
      sampleRate: opts.sampleRate,
      masterGain: opts.masterGain,
      voiceCount: opts.voiceCount,
      sidechain: opts.sidechain,
      busGains,
      busEQ: opts.busEQ,
      busSaturation: opts.busSaturation,
      masterFilter: opts.masterFilter,
      filterEnvelope: opts.filterEnvelope,
      filename,
      download: true,
    })

    results.push({
      bus,
      blob: result.blob,
      renderMs: result.renderMs,
      eventsRealized: result.eventsRealized,
      filename,
    })
  }

  const totalMs = performance.now() - t0

  // Phase 6.2: generate + download README.txt with project metadata.
  const readmeBlob = generateReadme(opts, totalMs)
  const readmeFilename = `${opts.baseFilename}_${bpmSuffix}README.txt`
  downloadBlob(readmeBlob, readmeFilename)

  return {
    stems: results,
    totalMs,
    readmeBlob,
  }
}
