#!/usr/bin/env bun
/**
 * Procedural sample generator for PSY Sampler MVP library.
 *
 * Generates 6 additional WAV samples (kick variants, perc, texture, bass)
 * to complement the 6 PSY3 procedural samples copied from psy4.
 *
 * All generated samples are:
 *   - Mono, 44100 Hz, 16-bit PCM WAV
 *   - Procedurally synthesized (no external audio, no copyright)
 *   - Licensed: "Procedurally generated by psy-sampler build script — no copyright restriction"
 *
 * Usage: bun run scripts/generate-samples.ts
 */

import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const SAMPLE_RATE = 44100
// @ts-ignore — import.meta.dir is a Bun runtime API
const OUTPUT_DIR = join(import.meta.dir, '..', 'public', 'samples')

// ─── WAV writer (16-bit PCM, mono) ───────────────────────────────────────────

function writeWav(filename: string, samples: Float32Array): void {
  const numSamples = samples.length
  const buffer = Buffer.alloc(44 + numSamples * 2)
  // RIFF header
  buffer.write('RIFF', 0)
  buffer.writeUInt32LE(36 + numSamples * 2, 4)
  buffer.write('WAVE', 8)
  buffer.write('fmt ', 12)
  buffer.writeUInt32LE(16, 16)
  buffer.writeUInt16LE(1, 20) // PCM
  buffer.writeUInt16LE(1, 22) // mono
  buffer.writeUInt32LE(SAMPLE_RATE, 24)
  buffer.writeUInt32LE(SAMPLE_RATE * 2, 28) // byte rate
  buffer.writeUInt16LE(2, 32) // block align
  buffer.writeUInt16LE(16, 34) // bits per sample
  buffer.write('data', 36)
  buffer.writeUInt32LE(numSamples * 2, 40)
  // Samples
  for (let i = 0; i < numSamples; i++) {
    let s = samples[i]
    s = Math.max(-1, Math.min(1, s))
    buffer.writeInt16LE(Math.round(s * 32767), 44 + i * 2)
  }
  writeFileSync(join(OUTPUT_DIR, filename), buffer)
  console.log(`  generated ${filename} (${numSamples} samples, ${(numSamples / SAMPLE_RATE).toFixed(3)}s)`)
}

// ─── DSP primitives ──────────────────────────────────────────────────────────

function expEnv(t: number, decay: number): number {
  return Math.exp(-t / decay)
}

function sine(freq: number, t: number): number {
  return Math.sin(2 * Math.PI * freq * t)
}

function noise(): number {
  return Math.random() * 2 - 1
}

// ─── Sample generators ───────────────────────────────────────────────────────

/** Deep kick: sine with pitch drop 80→45 Hz, longer decay. */
function genKickDeep(): Float32Array {
  const dur = 0.4
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const freq = 80 * Math.exp(-t * 8) + 45
    const env = expEnv(t, 0.25)
    const click = i < 100 ? noise() * expEnv(t, 0.003) * 0.3 : 0
    out[i] = (sine(freq, t) * env + click) * 0.9
  }
  return out
}

/** Punchy kick: sine with pitch drop 120→55 Hz, shorter decay. */
function genKickPunchy(): Float32Array {
  const dur = 0.25
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const freq = 120 * Math.exp(-t * 12) + 55
    const env = expEnv(t, 0.12)
    const click = i < 80 ? noise() * expEnv(t, 0.002) * 0.4 : 0
    out[i] = (sine(freq, t) * env + click) * 0.85
  }
  return out
}

/** Perc 1: short tonal hit (sine 200 Hz with fast decay + noise transient). */
function genPerc1(): Float32Array {
  const dur = 0.15
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const tone = sine(200 + t * 100, t) * expEnv(t, 0.05)
    const transient = i < 200 ? noise() * expEnv(t, 0.01) * 0.5 : 0
    out[i] = (tone + transient) * 0.7
  }
  return out
}

/** Perc 2: metallic-ish hit (two detuned sines + noise). */
function genPerc2(): Float32Array {
  const dur = 0.18
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const tone = (sine(440, t) + sine(554, t) * 0.6) * expEnv(t, 0.04)
    const transient = i < 150 ? noise() * expEnv(t, 0.008) * 0.4 : 0
    out[i] = (tone + transient) * 0.6
  }
  return out
}

/** Texture pad: filtered noise swell (atmospheric). */
function genTexturePad(): Float32Array {
  const dur = 2.0
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  // Simple low-pass on noise via running average.
  let prev = 0
  const lpCoeff = 0.005
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    // Attack-decay envelope (swell).
    const env = Math.min(1, t / 0.5) * Math.exp(-t / 1.5)
    prev = prev + (noise() - prev) * lpCoeff
    // Add a low drone.
    const drone = sine(55, t) * 0.3 + sine(82.5, t) * 0.2
    out[i] = (prev * 0.6 + drone) * env * 0.4
  }
  return out
}

/** Deep bass: saw-ish at A1 (55 Hz) with fast decay. */
function genBassDeep(): Float32Array {
  const dur = 0.5
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  let phase = 0
  const freq = 55
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    phase += freq / SAMPLE_RATE
    // Sawtooth via phase wrapping.
    const saw = (phase % 1) * 2 - 1
    // Simple one-pole lowpass for warmth.
    const env = expEnv(t, 0.2) * 0.5
    out[i] = saw * env * 0.7
  }
  return out
}

// ─── Additional sample generators ────────────────────────────────────────────

/** Snare: noise burst + tone body, fast decay. */
function genSnare(): Float32Array {
  const dur = 0.2
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const env = expEnv(t, 0.08)
    const noiseBurst = noise() * env * 0.6
    const tone = sine(180, t) * expEnv(t, 0.05) * 0.3
    out[i] = (noiseBurst + tone) * 0.8
  }
  return out
}

/** Shaker: filtered noise with short decay, softer than hat. */
function genShaker(): Float32Array {
  const dur = 0.08
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  let prev = 0
  const lpCoeff = 0.15
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const env = expEnv(t, 0.03)
    prev = prev + (noise() - prev) * lpCoeff
    out[i] = prev * env * 0.5
  }
  return out
}

/** Tom: sine with pitch drop 250→150 Hz, medium decay. */
function genTom(): Float32Array {
  const dur = 0.3
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const freq = 250 * Math.exp(-t * 5) + 150
    const env = expEnv(t, 0.15)
    out[i] = sine(freq, t) * env * 0.7
  }
  return out
}

/** Ride: metallic ping (multiple high sines + noise). */
function genRide(): Float32Array {
  const dur = 0.5
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const env = expEnv(t, 0.3)
    const metallic = (sine(1200, t) + sine(1800, t) * 0.6 + sine(2400, t) * 0.3) / 1.9
    const shimmer = noise() * 0.2
    out[i] = (metallic + shimmer) * env * 0.4
  }
  return out
}

/** Open hat: longer noise decay with HP filter simulation. */
function genOpenHat(): Float32Array {
  const dur = 0.3
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  let prev = 0
  const hpCoeff = 0.02
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const env = expEnv(t, 0.15)
    const raw = noise()
    prev = prev + (raw - prev) * hpCoeff
    const hp = raw - prev
    out[i] = hp * env * 0.4
  }
  return out
}

/** FX sweep: rising filter sweep for transitions. */
function genFxSweep(): Float32Array {
  const dur = 1.0
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  let prev = 0
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    const env = Math.min(1, t / 0.2) * Math.exp(-t / 0.8)
    // Rising filter cutoff
    const cutoff = 0.01 + (t / dur) * 0.3
    prev = prev + (noise() - prev) * cutoff
    out[i] = prev * env * 0.5
  }
  return out
}

/** Clap variant: multi-burst noise for variety. */
function genClapVariant(): Float32Array {
  const dur = 0.15
  const n = Math.floor(SAMPLE_RATE * dur)
  const out = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    // 3 quick bursts
    const burst1 = t < 0.01 ? noise() * expEnv(t, 0.005) : 0
    const burst2 = t >= 0.01 && t < 0.02 ? noise() * expEnv(t - 0.01, 0.005) : 0
    const burst3 = t >= 0.02 ? noise() * expEnv(t - 0.02, 0.08) : 0
    out[i] = (burst1 + burst2 + burst3) * 0.5
  }
  return out
}

// ─── Main ────────────────────────────────────────────────────────────────────

console.log('Generating procedural samples for PSY Sampler library...')

const samples: Array<{ name: string; gen: () => Float32Array }> = [
  { name: 'kick_deep.wav', gen: genKickDeep },
  { name: 'kick_punchy.wav', gen: genKickPunchy },
  { name: 'perc_1.wav', gen: genPerc1 },
  { name: 'perc_2.wav', gen: genPerc2 },
  { name: 'texture_pad.wav', gen: genTexturePad },
  { name: 'bass_deep.wav', gen: genBassDeep },
  { name: 'snare.wav', gen: genSnare },
  { name: 'shaker.wav', gen: genShaker },
  { name: 'tom.wav', gen: genTom },
  { name: 'ride.wav', gen: genRide },
  { name: 'open_hat_gen.wav', gen: genOpenHat },
  { name: 'fx_sweep.wav', gen: genFxSweep },
  { name: 'clap_variant.wav', gen: genClapVariant },
]

for (const s of samples) {
  const data = s.gen()
  writeWav(s.name, data)
}

console.log(`Done. ${samples.length} samples generated in ${OUTPUT_DIR}`)
